AWSTemplateFormatVersion: 2010-09-09
Description: Rootstack
Parameters:
  StackName:
    Type: String
    Description: GENERATED
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Disabled
          - NoncurrentVersionExpirationInDays: 7
            Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  ServiceRoleForCloudFormation:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StackName}-ServiceRoleForCloudFormation'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
          Action: ['sts:AssumeRole']
      Policies:
      - PolicyName: AdministratorAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: ["*"]
            Resource: ["*"]
Outputs:
  S3BucketName:
    Value: !Ref Bucket
  S3BucketSecureURL:
    Value: !Sub https://${Bucket.RegionalDomainName}
  IAMServiceRole:
    Value: !GetAtt ServiceRoleForCloudFormation.Arn
