AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB Table
Parameters:
  DynamoDbTableName: 
    Type: String
  DynamoDbTableArn:
    Type: String
  DynamoGsiLambda:
    Type: String
Resources:
  GsiTag0:
    Type: Custom::GsiTag0
    Properties:
      ServiceToken: !Ref DynamoGsiLambda
      TableName: !Ref DynamoDbTableName
      IndexName: Tag0
      AttributeDefinitions:
      - AttributeName: Tag0
        AttributeType: S
      KeySchema:
      - AttributeName: Tag0
        KeyType: HASH
      - AttributeName: EventTime
        KeyType: RANGE
      Projection:
        ProjectionType: INCLUDE
        NonKeyAttributes:
        - Message
      delete_on_update: True
