AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB Table
Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: UserId
        AttributeType: S
      - AttributeName: EventTime
        AttributeType: N
      KeySchema:
      - AttributeName: UserId
        KeyType: HASH
      - AttributeName: EventTime
        KeyType: RANGE
#      GlobalSecondaryIndexes:
#      - IndexName: Tag0
#        KeySchema:
#        - AttributeName: Tag0
#          KeyType: HASH
#        - AttributeName: EventTime
#          KeyType: RANGE
#        Projection:
#          ProjectionType: INCLUDE
#          NonKeyAttributes:
#          - Message

Outputs:
  Name:
    Value: !Ref UserTable
  Arn:
    Value: !GetAtt UserTable.Arn
