AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Table
Parameters:
  S3BucketSecureURL:
    Type: String
Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: UserId
        AttributeType: S
      - AttributeName: EventTime
        AttributeType: N
      KeySchema:
      - AttributeName: UserId
        KeyType: HASH
      - AttributeName: EventTime
        KeyType: RANGE
  DynamoGsiFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DynamoDbTableArn: !GetAtt DynamoDbTable.Arn
      TemplateURL: !Sub ${S3BucketSecureURL}/custom-resources/dynamodb-gsi/packaged.yaml
  GsiTag0:
    Type: Custom::GsiTag0
    Properties:
      ServiceToken: !GetAtt DynamoGsiFunction.Outputs.Arn
      TableName: !Ref DynamoDbTable
      IndexName: Tag0
      AttributeDefinitions:
      - AttributeName: Tag0
        AttributeType: S
      KeySchema:
      - AttributeName: Tag0
        KeyType: HASH
      - AttributeName: EventTime
        KeyType: RANGE
      Projection:
        ProjectionType: INCLUDE
        NonKeyAttributes:
        - Message
      delete_on_update: True
Outputs:
  Name:
    Value: !Ref DynamoDbTable
  Arn:
    Value: !GetAtt DynamoDbTable.Arn
