AWSTemplateFormatVersion: 2010-09-09
Description: Root stack
Parameters:
  S3BucketName:
    Type: String
    Description: GENERATED
  S3BucketSecureURL:
    Type: String
    Description: GENERATED
  IAMServiceRole:
    Type: String
  LastChange:
    Type: String
    Description: GENERATED
Resources:
  DynamoDbTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        S3BucketSecureURL: !Ref S3BucketSecureURL
      TemplateURL: !Sub ${S3BucketSecureURL}/dynamodb.yaml
  PostManagerApp:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Stage: prod
        S3BucketName: !Ref S3BucketName
        DynamoDbTableName: !GetAtt DynamoDbTable.Outputs.Name
        DynamoDbTableArn: !GetAtt DynamoDbTable.Outputs.Arn
      TemplateURL: !Sub ${S3BucketSecureURL}/post-manager/packaged.yaml
Outputs:
  EndpointUrl:
    Value: !GetAtt PostManagerApp.Outputs.Url
